#!/usr/bin/env python3
"""Generate hermes snippets, catalogue fragment, wrappers, env.example."""
from __future__ import annotations

import json
import os
import shlex
import stat
import textwrap
from pathlib import Path


def which_entry(target: Path, entrypoints: list[str] | None) -> tuple[str, list[str]] | None:
    """Return (command, args) best-effort for a checked-out component."""
    if not target.exists():
        return None

    # Prefer uv run project scripts when pyproject exists
    pyproject = target / "pyproject.toml"
    candidates = list(entrypoints or [])

    # Common patterns
    for rel in (
        "scripts/run_stdio.py",
        "server.py",
        "mcp-server/stdio_server.py",
        "src/proxy_server.py",
    ):
        if (target / rel).exists() and rel not in candidates:
            candidates.append(rel)

    venv_python = target / "venv" / "bin" / "python"
    uv_python_markers = pyproject.exists()

    for ep in candidates:
        if ep.startswith("fastmcp "):
            # fastmcp run path:mcp
            parts = ep.split()
            if uv_python_markers:
                return "uv", ["--directory", str(target), "run", *parts]
            return parts[0], parts[1:]
        if " -m " in f" {ep} " or ep.startswith("python -m"):
            mod = ep.replace("python -m", "").strip()
            if uv_python_markers:
                return "uv", ["--directory", str(target), "run", "python", "-m", *mod.split()]
            py = str(venv_python if venv_python.exists() else "python3")
            return py, ["-m", *mod.split()]
        # bare console script name
        if " " not in ep and not ep.endswith(".py") and "/" not in ep:
            if uv_python_markers:
                return "uv", ["--directory", str(target), "run", ep]
            return ep, []
        # file path
        rel = ep
        path = target / rel
        if path.exists():
            if uv_python_markers and rel != "mcp-server/stdio_server.py":
                return "uv", ["--directory", str(target), "run", "python", str(path)]
            py = str(venv_python if venv_python.exists() else "python3")
            return py, [str(path)]

    if (target / "mcp-server" / "stdio_server.py").exists():
        py = str(venv_python if venv_python.exists() else "python3")
        return py, [str(target / "mcp-server" / "stdio_server.py")]

    if (target / "src" / "proxy_server.py").exists():
        return "uv", ["--directory", str(target), "run", "--quiet", "python", "-m", "src.proxy_server"]

    return None


def main() -> int:
    root = Path(os.environ["ROOT"]).expanduser().resolve()
    catalog = json.loads(Path(os.environ["CATALOGUE_JSON"]).read_text(encoding="utf-8"))
    ids = [x for x in os.environ.get("COMPONENT_IDS", "").split() if x]
    dry = os.environ.get("DRY_RUN") == "1"
    gen = root / "GENERATED"
    bin_dir = root / "bin"
    if not dry:
        gen.mkdir(parents=True, exist_ok=True)
        bin_dir.mkdir(parents=True, exist_ok=True)

    comps = catalog["components"]
    hermes_lines: list[str] = ["# Generated by happymonkey-dev-ecosystem install.sh", "# Merge under mcp_servers: in Hermes config, or use hermes-register.sh", ""]
    register_lines: list[str] = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Non-interactive Hermes MCP registration for installed components",
        "",
    ]
    catalogue_entries: list[dict] = []
    env_keys: list[str] = []
    wrappers_written = 0
    mcp_json: dict = {"mcpServers": {}}

    for cid in ids:
        meta = comps[cid]
        target = root / meta["dir"]
        hermes = meta.get("hermes") or {}
        entrypoints = hermes.get("entrypoints")
        cmd_args = which_entry(target, entrypoints)

        # env hints
        for k in meta.get("env_hints") or []:
            if k not in env_keys:
                env_keys.append(k)

        # special path templates from catalogue (work without checkout)
        if hermes.get("command_template") and hermes.get("args_template"):
            cmd = (
                hermes["command_template"]
                .replace("${ROOT}", str(root))
                .replace("${DIR}", meta["dir"])
            )
            args = [
                a.replace("${ROOT}", str(root)).replace("${DIR}", meta["dir"])
                for a in hermes["args_template"]
            ]
            cmd_args = (cmd, args)

        # Fall back to documented entrypoints even if tree not present yet
        if not cmd_args and entrypoints:
            ep0 = entrypoints[0]
            tdir = str(target)
            if ep0.startswith("fastmcp "):
                parts = ep0.split()
                cmd_args = ("uv", ["--directory", tdir, "run", *parts])
            elif ep0.endswith(".py") or "/" in ep0:
                cmd_args = (
                    "uv",
                    ["--directory", tdir, "run", "python", str(target / ep0)],
                )
            elif " -m " in f" {ep0} " or ep0.startswith("python -m"):
                mod = ep0.replace("python -m", "").strip()
                cmd_args = (
                    "uv",
                    ["--directory", tdir, "run", "python", "-m", *mod.split()],
                )
            else:
                cmd_args = ("uv", ["--directory", tdir, "run", ep0])

        if meta.get("kind") == "proxy" and not cmd_args:
            cmd_args = (
                "uv",
                [
                    "run",
                    "--quiet",
                    "--project",
                    str(target),
                    "python",
                    "-m",
                    "src.proxy_server",
                ],
            )

        if not cmd_args:
            continue
        command, args = cmd_args

        # wrappers
        wname = f"hm-{cid}"
        wrapper_path = bin_dir / wname
        if command == "uv":
            body = "#!/usr/bin/env bash\nset -euo pipefail\nexec uv " + " ".join(
                shlex.quote(a) for a in args
            ) + ' "$@"\n'
        else:
            body = (
                "#!/usr/bin/env bash\nset -euo pipefail\nexec "
                + shlex.quote(command)
                + " "
                + " ".join(shlex.quote(a) for a in args)
                + ' "$@"\n'
            )
        if not dry:
            wrapper_path.write_text(body, encoding="utf-8")
            wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            wrappers_written += 1

        server_name = hermes.get("server_name") or cid.replace("-", "_")
        if hermes.get("register"):
            # YAML snippet
            hermes_lines.append(f"{server_name}:")
            hermes_lines.append(f"  command: {command}")
            hermes_lines.append("  args:")
            for a in args:
                hermes_lines.append(f"  - {json.dumps(a)}")
            hermes_lines.append("  enabled: true")
            hermes_lines.append("")

            # hermes mcp add
            args_csv = ",".join(args)
            register_lines.append(
                "printf 'y\\n' | hermes mcp add "
                + shlex.quote(server_name)
                + " --command "
                + shlex.quote(command)
                + " --args "
                + shlex.quote(args_csv)
            )
            mcp_json["mcpServers"][server_name] = {"command": command, "args": args}

        cname = meta.get("catalogue_name")
        if cname:
            catalogue_entries.append(
                {
                    "name": cname,
                    "description": meta.get("description") or meta.get("name") or cid,
                    "command": f"{command} " + " ".join(args) if args else command,
                    "tags": meta.get("tags") or [],
                    "tech_stack": ["python", "mcp"],
                    "runtime": "stdio",
                    "env_vars": meta.get("env_hints") or [],
                }
            )

    # env.example with sensible local defaults (no secrets)
    env_example = [
        "# Copy to $ROOT/.env and source before launching agents",
        f"export HM_ROOT={shlex.quote(str(root))}",
        f"export PATH={shlex.quote(str(bin_dir))}:$PATH",
        f"export AGENT_CLI_PROFILES_DIR={shlex.quote(str(root / 'ai-agent-teamwork-prompt' / 'profiles'))}",
        f"export LAUNCHER_REGISTRY_PATH={shlex.quote(str(root / 'launcher-project-registry' / 'registry.json'))}",
        f"export USER_CONTEXT_ROOT={shlex.quote(str(root / 'user-context-mcp' / 'context'))}",
        f"export ARTICLE_RESEARCH_ROOT=$HOME/research",
        "# Optional local OpenAI-compatible endpoint for ranking/scoring",
        "# export OPENAI_COMPAT_BASE_URL=http://127.0.0.1:11434/v1",
        "# export OPENAI_COMPAT_API_KEY=ollama",
        "# export OPENAI_COMPAT_MODEL=llama3.2",
        "",
    ]
    for k in env_keys:
        if k in {
            "AGENT_CLI_PROFILES_DIR",
            "LAUNCHER_REGISTRY_PATH",
            "USER_CONTEXT_ROOT",
            "ARTICLE_RESEARCH_ROOT",
            "OPENAI_COMPAT_BASE_URL",
            "OPENAI_COMPAT_API_KEY",
            "OPENAI_COMPAT_MODEL",
        }:
            continue
        env_example.append(f"# export {k}=")

    if not dry:
        (gen / "hermes-mcp.snippet.yaml").write_text("\n".join(hermes_lines) + "\n", encoding="utf-8")
        reg = gen / "hermes-register.sh"
        reg.write_text("\n".join(register_lines) + "\n", encoding="utf-8")
        reg.chmod(reg.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        (gen / "user.catalogue.fragment.json").write_text(
            json.dumps(catalogue_entries, indent=2) + "\n", encoding="utf-8"
        )
        (gen / "env.example").write_text("\n".join(env_example) + "\n", encoding="utf-8")
        (gen / "mcp.json").write_text(json.dumps(mcp_json, indent=2) + "\n", encoding="utf-8")
        (gen / "installed-components.json").write_text(
            json.dumps({"root": str(root), "components": ids}, indent=2) + "\n",
            encoding="utf-8",
        )

    print(
        json.dumps(
            {
                "root": str(root),
                "wrappers": wrappers_written,
                "catalogue_entries": len(catalogue_entries),
                "hermes_servers": len(mcp_json["mcpServers"]),
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
